### PR TITLE
Todo List

### PR DESCRIPTION
**Pull request by yokoworks**
We created Todo Desktop Application with JavaScript. 
**In this application, Users can:**
- Create a to-do list that is saved at the user's local storage
- Arrange todos for different projects
- Create or remove a project and add as many todos as they want to each project
- Edit or remove todos

**We built this application taking care of:** 
- Organized files and functions based on the MVC concept
- Helper functions to create DOM elements efficiently
- Put a tag to each todo corresponding to its priority with different colors
- Add default data in order to show how to use this app for users

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @yocosaka  & @Zappat0n**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

I like the way that you structured your project, but there is a problem with your project.

- [x] when I try to do anything i.e. create a todo, update a todo, create a project the UI goes like this: 
sad

this behavior only happens if it's the first time I try to run the project. if I reload the page the changes are implemented and the UI starts working fine. but if I clear the cookies, it starts to happen again.  please make sure to find a way to solve this problem and request another review.

p.s.  this problem happens on both local and live versions.

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by yokoworks** [comment]
Hi @mahmoud717, thanks a lot for your great suggestion, but the same problem doesn't occur in both our local environment and the Netlify server in our browsers. Just in case, we checked the web app in some different browsers after removing cookies and data in localStoarge, but that kind of problem didn't happen. So we couldn't know how to fix it and what causes it. I'm sorry but it might happen because of your internet connection.

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello team,
Great implementation of the project. I really love the UI and the way it is easy to use.
However one small improvement to get it approved.

[REQUIRED]: In the readme file, specify how to run it locally.

That's it. Make the changes and ask for another review👍👏

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**

Great work implementing the changes.
You can merge the branches.👌

**Pull request merged**
